- name: Create login group
  ansible.builtin.group:
    name: "{{ ssh_login_group }}"
    gid: 2000

- name: Create login user
  ansible.builtin.user:
    name: "{{ ssh_login_user }}"
    uid: 2000
    groups:
      - sudo
    create_home: true

- name: Add authorized key for login user
  ansible.posix.authorized_key:
    user: "{{ ssh_login_user }}"
    key: "{{ ssh_login_public_key }}"
    exclusive: true

- name: Disable login for root user
  ansible.builtin.user:
    name: root
    password: '*'

- name: Remove all authorized keys from root user
  ansible.builtin.file:
    path: /root/.ssh/authorized_keys
    state: absent

- name: Disable login for pi user
  ansible.builtin.user:
    name: pi
    password: '*'

- name: Remove all authorized keys from pi user
  ansible.builtin.file:
    path: /home/pi/.ssh/authorized_keys
    state: absent
